package_dir = "./"
data_path = "/allen/programs/celltypes/workgroups/mousecelltypes/Yeganeh/CTX-HIP/mouse/brain_map_10x/"
local_data_path =  "./data/" #"/home/yeganeh/Remote-AI-root/CTX-HIP/mouse/brain_map_10x/"
data_gaba_1 = "./GABAergic_isoCTX_nGene_4886_2023-02-08-01-46-40.h5ad"
#data_gaba = "./GABAergic_isoCTX_nGene_20236_2023-03-23-11-10-22.h5ad"
data_gaba = "./GABAergic_isoCTX_nGene_10000.h5ad"
#data_gaba = "./brain_map_smartseq/isoCTX_nGene_20431_2023-06-01-23-54-24.h5ad"
data_glum_1 = "./Glutamatergic_isoCTX_nGene_4886_2023-02-08-01-46-40.h5ad"
#data_glum = "./Glutamatergic_isoCTX_nGene_20236_2023-03-30-12-31-08.h5ad"
data_glum = "./Glutamatergic_isoCTX_nGene_10000.h5ad"
data_L2-3_IT = "./L2-3_IT_isoCTX_nGene_20236.h5ad"
data_L4-5_IT = "./L4-5_IT_isoCTX_nGene_20236.h5ad"
data_L6_CT = "./L6_CT_isoCTX_nGene_20236.h5ad"
data_Vip = "./Vip_isoCTX_nGene_20236.h5ad"
data_Pvalb = "./Pvalb_isoCTX_nGene_20236.h5ad"
genes = "./data/facs_genes.csv"
ccf_file = "./data/isocortex_ccf.csv"
dend_file = "./data/dend.csv"
saving_folder_cplmix = "./results/cplmixVAE/"
saving_folder_augmenter = "./results/augmenter/"
aug_file_gaba = "./augmenter_gaba_ngene_10000"
aug_file_glum = "./augmenter_glum_ngene_10000"
cplmix_gaba = "./gaba_run_2_K_100_Sdim_3_aug_True_p_drop_0.5_fc_dim_100_temp_1_lr_0.001_n_arm_2_tau_0.005_lam_1_nbatch_5000_nepoch_10000_nepochP_1000"
cplmix_glum = "./"
ann_smt = "./data/metadata_smart.csv"
ann_10x = "./data/metadata_10x.csv"
trained_model = "/model/cpl_mixVAE_model_after_pruning_32_2023-06-06-12-45-37.pth"
